<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Parsedown' => array($vendorDir . '/erusev/parsedown'),
    'Hautelook' => array($vendorDir . '/bordoni/phpass/src'),
    'Analog' => array($vendorDir . '/analog/analog/lib'),
);
